[package]
name = "openrpc-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
schemars = "0.8.16"
serde = { version = "1.0.197", features = ["derive"] }
tap = "1.0.1"
thiserror = "1.0.57"
